routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HotelController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\TypeRoomController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\Auth\{LoginController, RegisterController, ResetPasswordController};
use App\Http\Middleware\{User, Admin};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
# Login & Register & Forgot password
Route::post('/send_login', [LoginController::class, 'sendLogin'])->name('sendLogin');
Route::post('/send_register', [RegisterController::class, 'sendRegister'])->name('sendRegister');
Route::post('/send_email_password', [ResetPasswordController::class, 'sendEmailPassword'])->name('sendEmailPassword');
Route::get('/logout', [LoginController::class, 'doLogout'])->name('doLogout');
Route::get('/logoutadmin',[LoginController::class,'doLogoutAdmin'])->name('doLogoutAdmin');
# End Login & Register & Forgot password
# Customer
Route::get('/user_profile', [CustomerController::class, 'index'])->name('profile')->middleware(User::class);
Route::get('/user_profile_edit', [CustomerController::class, 'showPageEdit'])->name('showPageEdit')->middleware(User::class);
Route::post('/send_user_edit', [CustomerController::class, 'doUserEdit'])->name('doUserEdit')->middleware(User::class);
Route::post('/changeavatar',[CustomerController::class,'changeAvatar'])->middleware(User::class);
Route::get('/user_password_change', [CustomerController::class, 'showPasswordChange'])->name('showPasswordChange')->middleware(User::class);
Route::post('/send_password_change', [CustomerController::class, 'doChangePassword'])->name('doChangePassword')->middleware(User::class);
Route::get('/history',[CustomerController::class, 'showHistory'])->name('showHistory')->middleware(User::class);
# End customer

Route::get('/', [HotelController::class,'home'])->name('home');
Route::get('/room', [HotelController::class,'room'])->name('room');
Route::get('/about', [HotelController::class,'aboutus'])->name('aboutus');
Route::get('/cart',[CustomerController::class,'showCart'])->name('cart');
Route::get('/detailroom={id}',[HotelController::class,'detailroom'])->name('detailroom');
Route::get('/admin/employee',[AdminController::class,'employee'])->name('employee')->middleware(Admin::class);
Route::post('/postRate/{id}', [HotelController::class, 'postRate'])->name('postrate')->middleware(User::class);
Route::get('/admin',[AdminController::class,'index'])->name('adminindex')->middleware(Admin::class);
Route::get('/admin/profile',[AdminController::class,'profile'])->name('adminprofile')->middleware(Admin::class);
Route::put('/admin/profile',[AdminController::class,'editprofile'])->name('updateprofile')->middleware(Admin::class);
Route::put('/admin/profile/newpass',[AdminController::class,'doChangePassword'])->name('changepassadmin')->middleware(Admin::class);
Route::put('/admin/profile/newavatar',[AdminController::class,'changeAvatar'])->name('changeavatar')->middleware(Admin::class);
Route::resource('rooms', RoomController::class)->middleware(Admin::class);
Route::resource('types', TypeRoomController::class)->middleware(Admin::class);
Route::resource('bookings', BookingController::class)->middleware(Admin::class);
Route::resource('employees', EmployeeController::class)->middleware(Admin::class);
Route::resource('services', ServiceController::class)->middleware(Admin::class);
Route::resource('message', MessageController::class)->middleware(Admin::class);
Route::get('/contact', [MessageController::class,'create'])->name('contact');
Route::get('/profile',[CustomerController::class,'index'])->name('profile')->middleware(User::class);
Route::get('/bookings/bill/{id}',[BookingController::class,'printbill'])->name('bill')->middleware(Admin::class);
Route::delete('/cart/{id}',[CustomerController::class,'destroy'])->name('deletecart')->middleware(User::class);
#Resetpass with mail
Route::get('/resetpassword=token={token}',[CustomerController::class,'getChangePass']);
Route::post('/change-password-with-token',[CustomerController::class,'postChangePass']);


// Route::get('/admin/room',[RoomController::class,'index'])->name('adminrooms');
// Route::get('/admin/user',[UserController::class,'index'])->name('adminusers');
// Route::get('/admin/booking',[BookingController::class,'index'])->name('adminbookings');
// Route::get('/admin/employee',[EmployeeController::class,'index'])->name('adminemployees');
// Route::get('/admin/services',[ServiceController::class,'index'])->name('adminservices');
// Route::get('/admin/user/create',[UserController::class,'create'])->name('usercreate');
Route::resource('users', UserController::class);
Route::get('/reset',function(){
    return view('emails.mailreset');
});
Route::get('/admin/bill', function(){
    return view('admin.bookings.bill');
});
Route::get('/admin/login', function() {
    return view('admin.login');
});
Route::get('admin/editbooking',function(){
return view('admin.bookings.editbooking');
});
Route::post('/send-login-admin', [LoginController::class, 'doLoginAdmin']);
// Route::get('/admin/rooms/edit', function() {
//     return view('admin.rooms.editroom');
// });
Route::post('/room/{id}',[CustomerController::class,'pushToCart'])->name('pushToCart')->middleware(User::class);
Route::put('/sendBookingToAdmin/{id}',[CustomerController::class,'sendBookingToAdmin'])->name('sendBookingToAdmin')->middleware(User::class);
Route::get('/cart/{id}',[CustomerController::class,'cartAjax'])->middleware(User::class);




//Multiple langue
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

app/Models/Booking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Room;
use App\Models\User;
use App\Models\Service;

class Booking extends Model
{
    use HasFactory, SoftDeletes;
    protected $table = 'bookings';
    protected $guarded = [];
    protected $hidden = [
        'deleted_at'
        ];
    public function rooms(){
        return $this->belongsTo(Room::class,'room_id');
    }
    public function users(){
        return $this->belongsTo(User::class,'user_id');
    }
    public function services(){
        return $this->belongsTo(Service::class,'service_id');
    }
}

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Illuminate\Support\Facades\Auth;
use App\Models\{Booking,Service,User,Room};

class BookingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        $query = Booking::query();
        if($request->status){
            $status = $request->status;
            $query = $query
                        ->where('bookings.status','=', $status );
        }
        if($request->username){
            $username = $request->username;
            $query = $query
                        ->join('users', 'users.id', '=', 'bookings.user_id')
                        ->select('bookings.*','users.name')
                        ->where('users.name', 'LIKE', "%" . $username . "%");
        }
        if($request->idroom){
            $idroom = $request->idroom;
            $query = $query
                ->join('rooms', 'rooms.id', '=', 'bookings.room_id')
                ->where('rooms.id', '=', $idroom);
        }
        if($request->typeroom){
            $type = $request->typeroom;
            $query = $query
                    ->join('rooms', 'rooms.id', '=', 'bookings.room_id')
                    ->where('type_id','=',$type);
        }
        // dd($query->get());
        $bookings = $query->with('rooms','services','users')->orderByDesc('bookings.created_at')->paginate(20);
        // dd($bookings);
        return view('admin.bookings.booking',compact('bookings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $services = Service::all();
        $users = User::all();
        return view('admin.bookings.createbooking',compact(['services','users']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'room'=>'required|numeric',
            'service'=>'required|numeric',
            'user' => 'required|numeric',
            'checkin' => 'required|date',
            'checkout' => 'required|date',
            'total' => 'required|numeric',
            'status' => 'required|numeric',
        ]);
        $booking = new Booking;
        $booking->room_id = $request->room;
        $booking->service_id = $request->service;
        $booking->user_id = $request->user;
        $booking->check_in = $request->checkin;
        $booking->check_out = $request->checkout;
        $booking->total = $request->total;
        $booking->status = $request->status;
        $booking->created_by = Auth::id();
        $booking->updated_by = Auth::id();
        $booking->save();
        return redirect('/bookings')->with('message','Booking created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $booking = Booking::find($id);
        $services = Service::all();
        $users = User::all();
        return view('admin.bookings.editbooking',compact(['booking','services','users']));
    }
     /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function printbill($id)
    {
        $booking = Booking::find($id);
        return view('admin.bookings.bill',compact("booking"));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'room'=>'required|numeric',
            'service'=>'required|numeric',
            'user' => 'required|numeric',
            'checkin' => 'required|date',
            'checkout' => 'required|date',
            'total' => 'required|numeric',
            'status' => 'required|numeric',
        ]);
        $booking = Booking::find($id);
        $booking->room_id = $request->room;
        $booking->service_id = $request->service;
        $booking->user_id = $request->user;
        $booking->check_in = $request->checkin;
        $booking->check_out = $request->checkout;
        $booking->total = $request->total;
        $booking->status = $request->status;
        $booking->updated_by = Auth::id();
        $booking->update();
        return redirect('/bookings')->with('message','Booking updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $booking = Booking::find($id);
        $booking->delete();
        return redirect('/bookings')->with('message','Booking deleted!');
    }
}

resources/views/admin/bookings/booking.blade.php
@extends('adminLayout')
@section('content')

<div class="right_col" style="min-height: 953px;">
    <h1 style="text-align:center;">Bookings</h1>
    <form action="" method="GET" class="frmsearch" id="searchform">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text widthcol2" id="basic-addon1" style="width: 95px;">User:</span>
                        </div>
                        <input type="text" id="name" class="form-control" name="username" placeholder="Enter name user"
                            aria-label="Username" aria-describedby="basic-addon1" value="{{request()->get('username')}}"
                            maxlength="115">
                    </div>
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text widthcol2" id="basic-addon1" style="width: 95px;">Type
                                room:</span>
                        </div>
                            <select name="typeroom" id="" value="{{request()->get('typeroom')}}" class="form-control">
                                <option value="0">All</option>
                                <option value="1">Standard Room</option>
                                <option value="2">Intermediate Room</option>
                                <option value="3">Luxury Room</option>
                                <option value="4">VIP Room</option>
                                <option value="5">Presidential Room</option>
                            </select>
                    </div>
                </div>
            </div>
            <div class=row>
                <div class="col">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text widthcol2" id="basic-addon1" style="width: 95px;">ID
                                room:</span>
                        </div>
                        <input type="text" id="id" class="form-control" name="idroom" placeholder="Enter id room"
                            aria-label="Username" aria-describedby="basic-addon1" value="{{request()->get('idroom')}}">
                    </div>
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text widthcol2" id="basic-addon1"
                                style="width: 95px;">Status:</span>
                        </div>
                            <select id="" class="form-control" name="status" value="{{request()->get('status')}}">
                                <option value="">All</option>
                                <option value="1">In Booking Cart</option>
                                <option value="2">Need Confirm</option>
                                <option value="3">Confirmation</option>
                                <option value="4">Paid</option>
                            </select>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row" style="margin: 20px">
                    <div class="col-md-4"></div>
                    <div class=" col-12 col-ms-8 col-md-8 col-xs-6">
                        <button type="submit" class="btn btn-primary col search" style="width:25%;">Search</button>
                    <a href="{{route('bookings.create')}}" class="">
                            <button type="button" class="btn btn-info col" style="width:25%;">Create</button>
                        </a>
                    </div>
                </div>
            </div>
    </form>
    <div class="row mt-2">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_content">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">STT</th>
                <th scope="col">ID room</th>
                <th scope="col">Type room</th>
                <th scope="col">User</th>
                <th scope="col">Check in</th>
                <th scope="col">Check out</th>
                <th scope="col">Service</th>
                <th scope="col">Price</th>
                <th scope="col">Total</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php $count = 1; ?>
            @foreach($bookings as $booking)
            <tr>
                <th scope="row">{{$bookings->perPage()*($bookings->currentPage()-1)+$count}}</th>
                <td>{{$booking->room_id}}</td>
                <td>{{$booking->rooms->types->name}}</td>
                <td>{{$booking->users->name}}</td>
                <td>{{Carbon\Carbon::parse($booking->check_in)->format('d-m-Y')}}</td>
                <td>{{Carbon\Carbon::parse($booking->check_out)->format('d-m-Y')}}</td>
                <td>{{$booking->services->price}}$</td>
                <td>{{$booking->rooms->types->price*$booking->rooms->amount_user}}$</td>
                <td>{{$booking->total}}$</td>
                @if ($booking->status == 1)
                <td>In Booking Cart</td>
                @elseif($booking->status == 2)
                <td>Need Confirm</td>
                @elseif($booking->status == 3)
                <td>Confirmation</td>
                @elseif($booking->status == 4)
                <td>Paid</td>
                @endif
                <td style="display: flex;">
                    <a href="{{route('bookings.edit', $booking->id)}}" style="color:blue;">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-pencil-square"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd"
                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                    </a>
                    <a href="" data-toggle="modal" data-target="#exampleModal"
                        onClick="onClickDelete({{$booking->id}})" style="color:red;">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd"
                                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                <a href="{{route('bill',$booking->id)}}" style="color:green;">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-printer" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M11 2H5a1 1 0 0 0-1 1v2H3V3a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v2h-1V3a1 1 0 0 0-1-1zm3 4H2a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h1v1H2a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1z" />
                            <path fill-rule="evenodd"
                                d="M11 9H5a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1zM5 8a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H5z" />
                            <path d="M3 7.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z" />
                        </svg>
                    </a>
                </td>
            </tr>
            <?php $count++; ?>
            @endforeach
        </tbody>
    </table>
    <form style="display:inline" action="" method="post" id="delete-form">
        @csrf
        @method('DELETE')
        <div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content" style="border-radius: 1rem;">
                    <div class="modal-header" style="background-color: #2A3F54;">
                        <h5 class="modal-title" id="exampleModalLabel" style="color:white;">DELETE</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h1 style="text-align:center;">Are you sure?</h1>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"
                            style="width: 100px;">Close</button>
                        <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#successdelete"
                            onClick="submitdelete()" style="width: 67px;">Yes</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="d-flex justify-content-end nav">
        {!! $bookings->withQueryString()->links('pagination.paginate') !!}
    </div>
    </div>
    </div>
        </div>
    </div>
</div>
@if (Session::has('message'))
<div id="snackbar">{{ Session::get('message') }}</div>
<script>
    var x = document.getElementById("snackbar");
    x.className = "show";
    setTimeout(function() {
        x.className = x.className.replace("show", "");
    }, 3000);

</script>
</div>
@endif
<script>
    const onClickDelete = (id) => {
        const deleteForm = document.getElementById('delete-form');
        deleteForm.action = '/bookings/' + id;
    };
    
    function submitdelete() {
        deleteForm.submit();
    }
    </script>
@endsection

resources/views/admin/bookings/createbooking.blade.php
@extends('adminLayout')
@section('content')
<div class="right_col" style="min-height: 953px;">
    <div class="row mt-2">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_content">
    <h1 style="text-align: center;">Create Booking</h1>
<form action="{{route('bookings.store')}}" method="POST" id="form-create">
        @csrf  
        <div class="form-group">
        <label for="">Room id:</label>
        <input type="number" name="room" id="" class="form-control">
        </div>
        <div class="form-group">
        <label for="">Service:</label>
        <select name="service" id="" class="form-control">
            @foreach ($services as $service)
            <option value="{{$service->id}}">{{$service->name}}</option>
            @endforeach
        </select>
        </div>
        <div class="form-group">
        <label for="">User:</label>
        <select name="user" id="" class="form-control">
            @foreach ($users as $user)
            <option value="{{$user->id}}">{{$user->name}}</option>
            @endforeach
        </select>
        </div>
        <div class="form-group">
        <label for="">Check-in:</label>
        <input type="date" name="checkin" id="" class="form-control">
        </div>
        <div class="form-group">
        <label for="">Check-out:</label>
        <input type="date" name="checkout" id="" class="form-control">
        </div>
        <div class="form-group">
        <label for="">Total:</label>
        <input type="number" name="total" id="" class="form-control">
        </div>
        <div class="form-group">
        <label for="">Status:</label>
        <select name="status" id="" class="form-control">
            <option value="3">Confirmation</option>
            <option value="4">Paid</option>
        </select>
        </div>
        <button class="btn btn-secondary" style="margin-left: 45%;margin-top: 20px;">Submit</button>
    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@if ($errors->any())
            <div id="snackbar">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
                <script>
                    var x = document.getElementById("snackbar");
                    x.className = "show";
                    setTimeout(function() {
                        x.className = x.className.replace("show", "");
                    }, 5000);
                </script>
            <br />
        @endif
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
    <script>
    $("#form-create").validate({
    rules: {
        room: {
            required: true,
            maxlenght: 2000,
            number: true,
        },
        user: {
            required: true,
        },
        service: {
            required: true,
        },
        checkin: {
            required: true,
            date: true,
        },
        checkout: {
            required: true,
            date: true,
        },
        total: {
            required: true,
            maxlenght: 2000,
            number: true,
        },
        status: {
            required: true,
        }
    },
    errorElement: 'span',
    errorPlacement: function(error, element) {
        error.addClass('invalid-feedback');
        element.closest('.form-group').append(error);
    },
    highlight: function(element, errorClass, validClass) {
        $(element).addClass('is-invalid');
    },
    unhighlight: function(element, errorClass, validClass) {
        $(element).removeClass('is-invalid');
    }
});
</script>
@endsection

resources/views/admin/bookings/editbooking.blade.php
@extends('adminLayout')
@section('content')
<div class="right_col" style="min-height: 953px;">
    <div class="row mt-2">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_content">
    <h1 style="text-align: center;">Edit Booking</h1>
<form action="{{route('bookings.update',$booking)}}" method="post">
    @method('put')
        @csrf
        <label for="">Room id:</label>
        <input type="number" name="room" id="" class="form-control" value="{{$booking->room_id}}">
        <label for="">Service:</label>
        <select name="service" id="" class="form-control">
            @foreach ($services as $service)
            <option value="{{$service->id}}">{{$service->name}}</option>
            @endforeach
        </select>
        <label for="">User:</label>
    <select name="user" id="" class="form-control" >
    <option value="{{$booking->user_id}}">{{$booking->users->name}}</option>
            @foreach ($users as $user)
            <option value="{{$user->id}}">{{$user->name}}</option>
            @endforeach
        </select>
        <label for="">Check-in:</label>
    <input type="date" name="checkin" id="" class="form-control" value="{{Carbon\Carbon::parse($booking->check_in)->format('Y-m-d')}}">
        <label for="">Check-out:</label>
    <input type="date" name="checkout" id="" class="form-control" value="{{Carbon\Carbon::parse($booking->check_out)->format('Y-m-d')}}">
        <label for="">Total:</label>
    <input type="number" name="total" id="" class="form-control" value="{{$booking->total}}">
        <label for="">Status:</label>
        <select name="status" id="" class="form-control">
            @if($booking->status == 1)
            <option value="1">In Booking Cart</option>
            <option value="2">Need Confirm</option>
            <option value="3">Confirmation</option>
            <option value="4">Paid</option>
            @elseif($booking->status == 2)
            <option value="2">Need Confirm</option>
            <option value="3">Confirmation</option>
            <option value="4">Paid</option>
            @elseif($booking->status == 3)
            <option value="3">Confirmation</option>
            <option value="2">Need Confirm</option>
            <option value="4">Paid</option>
            @elseif($booking->status == 4)
            <option value="4">Paid</option>
            <option value="3">Confirmation</option>
            @endif
        </select>
        <button class="btn btn-secondary" style="margin-left: 45%;margin-top: 20px;">Submit</button>
    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@if ($errors->any())
            <div id="snackbar">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
                <script>
                    var x = document.getElementById("snackbar");
                    x.className = "show";
                    setTimeout(function() {
                        x.className = x.className.replace("show", "");
                    }, 3000);
                </script>
            <br />
        @endif
@endsection