routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HotelController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\TypeRoomController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\Auth\{LoginController, RegisterController, ResetPasswordController};
use App\Http\Middleware\{User, Admin};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
# Login & Register & Forgot password
Route::post('/send_login', [LoginController::class, 'sendLogin'])->name('sendLogin');
Route::post('/send_register', [RegisterController::class, 'sendRegister'])->name('sendRegister');
Route::post('/send_email_password', [ResetPasswordController::class, 'sendEmailPassword'])->name('sendEmailPassword');
Route::get('/logout', [LoginController::class, 'doLogout'])->name('doLogout');
Route::get('/logoutadmin',[LoginController::class,'doLogoutAdmin'])->name('doLogoutAdmin');
# End Login & Register & Forgot password
# Customer
Route::get('/user_profile', [CustomerController::class, 'index'])->name('profile')->middleware(User::class);
Route::get('/user_profile_edit', [CustomerController::class, 'showPageEdit'])->name('showPageEdit')->middleware(User::class);
Route::post('/send_user_edit', [CustomerController::class, 'doUserEdit'])->name('doUserEdit')->middleware(User::class);
Route::post('/changeavatar',[CustomerController::class,'changeAvatar'])->middleware(User::class);
Route::get('/user_password_change', [CustomerController::class, 'showPasswordChange'])->name('showPasswordChange')->middleware(User::class);
Route::post('/send_password_change', [CustomerController::class, 'doChangePassword'])->name('doChangePassword')->middleware(User::class);
Route::get('/history',[CustomerController::class, 'showHistory'])->name('showHistory')->middleware(User::class);
# End customer

Route::get('/', [HotelController::class,'home'])->name('home');
Route::get('/room', [HotelController::class,'room'])->name('room');
Route::get('/about', [HotelController::class,'aboutus'])->name('aboutus');
Route::get('/cart',[CustomerController::class,'showCart'])->name('cart');
Route::get('/detailroom={id}',[HotelController::class,'detailroom'])->name('detailroom');
Route::get('/admin/employee',[AdminController::class,'employee'])->name('employee')->middleware(Admin::class);
Route::post('/postRate/{id}', [HotelController::class, 'postRate'])->name('postrate')->middleware(User::class);
Route::get('/admin',[AdminController::class,'index'])->name('adminindex')->middleware(Admin::class);
Route::get('/admin/profile',[AdminController::class,'profile'])->name('adminprofile')->middleware(Admin::class);
Route::put('/admin/profile',[AdminController::class,'editprofile'])->name('updateprofile')->middleware(Admin::class);
Route::put('/admin/profile/newpass',[AdminController::class,'doChangePassword'])->name('changepassadmin')->middleware(Admin::class);
Route::put('/admin/profile/newavatar',[AdminController::class,'changeAvatar'])->name('changeavatar')->middleware(Admin::class);
Route::resource('rooms', RoomController::class)->middleware(Admin::class);
Route::resource('types', TypeRoomController::class)->middleware(Admin::class);
Route::resource('bookings', BookingController::class)->middleware(Admin::class);
Route::resource('employees', EmployeeController::class)->middleware(Admin::class);
Route::resource('services', ServiceController::class)->middleware(Admin::class);
Route::resource('message', MessageController::class)->middleware(Admin::class);
Route::get('/contact', [MessageController::class,'create'])->name('contact');
Route::get('/profile',[CustomerController::class,'index'])->name('profile')->middleware(User::class);
Route::get('/bookings/bill/{id}',[BookingController::class,'printbill'])->name('bill')->middleware(Admin::class);
Route::delete('/cart/{id}',[CustomerController::class,'destroy'])->name('deletecart')->middleware(User::class);
#Resetpass with mail
Route::get('/resetpassword=token={token}',[CustomerController::class,'getChangePass']);
Route::post('/change-password-with-token',[CustomerController::class,'postChangePass']);


// Route::get('/admin/room',[RoomController::class,'index'])->name('adminrooms');
// Route::get('/admin/user',[UserController::class,'index'])->name('adminusers');
// Route::get('/admin/booking',[BookingController::class,'index'])->name('adminbookings');
// Route::get('/admin/employee',[EmployeeController::class,'index'])->name('adminemployees');
// Route::get('/admin/services',[ServiceController::class,'index'])->name('adminservices');
// Route::get('/admin/user/create',[UserController::class,'create'])->name('usercreate');
Route::resource('users', UserController::class);
Route::get('/reset',function(){
    return view('emails.mailreset');
});
Route::get('/admin/bill', function(){
    return view('admin.bookings.bill');
});
Route::get('/admin/login', function() {
    return view('admin.login');
});
Route::get('admin/editbooking',function(){
return view('admin.bookings.editbooking');
});
Route::post('/send-login-admin', [LoginController::class, 'doLoginAdmin']);
// Route::get('/admin/rooms/edit', function() {
//     return view('admin.rooms.editroom');
// });
Route::post('/room/{id}',[CustomerController::class,'pushToCart'])->name('pushToCart')->middleware(User::class);
Route::put('/sendBookingToAdmin/{id}',[CustomerController::class,'sendBookingToAdmin'])->name('sendBookingToAdmin')->middleware(User::class);
Route::get('/cart/{id}',[CustomerController::class,'cartAjax'])->middleware(User::class);




//Multiple langue
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Type;
use App\Models\Booking;

class Room extends Model
{
    use SoftDeletes;
    use HasFactory;
    protected $table = 'rooms';
    protected $guarded = [];
    protected $hidden = [
        'deleted_at'
        ];
    public function types(){
        return $this->belongsTo(Type::class,'type_id');
    }
    public function bookings(){
        return $this->hasMany(Booking::class);
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Models\Room;
use App\Models\Type;
use App\Models\Booking;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;
class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = Room::join('types','rooms.type_id','=','types.id');
        $rooms = $query
                    ->select('rooms.*','types.name as type_name','types.price as type_price')
                    ->paginate(10);
        if($request->id){
            $id = $request->id;
            $rooms= $query
                        ->where('rooms.id',$id)
                        ->paginate(10);
        }
        if($request->type){
            $type = $request->type;
            $rooms= $query
                        ->where('types.name','LIKE', "%" . $type . "%")
                        ->paginate(10);
        }
        if($request->status){
            $status = $request->status;
            $rooms = $query
                    ->where('rooms.status',$status)
                    ->paginate(10);
        }
        return view('admin.rooms.room', compact('rooms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rooms = Room::all();
        return view('admin.rooms.createroom',['rooms'=>$rooms]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'img1'=>'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'img2'=>'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'img3' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'type_id' => 'required|numeric',
            'description' => 'required|max:1000',
            'amount_user' => 'required|numeric',
            'status' => 'required|numeric',
        ]);
        $file_name1 = '';
        $file_name2 = '';
        $file_name3 = '';
        if ($request->file('img1')) {
            $destinationPath = public_path('images/rooms');
            $files = $request->file('img1');
            $file_name = $files->getClientOriginalName(); 
            $file_name1 = $file_name;
            $files->move($destinationPath , $file_name); 
        } 
        if ($request->file('img2')) {
            $destinationPath = public_path('images/rooms');
            $files = $request->file('img2');
            $file_name = $files->getClientOriginalName();
            $file_name2 = $file_name; 
            $files->move($destinationPath , $file_name); 
        } 
        if ($request->file('img3')) {
            $destinationPath = public_path('images/rooms');
            $files = $request->file('img3');
            $file_name = $files->getClientOriginalName(); 
            $file_name3 = $file_name;
            $files->move($destinationPath , $file_name); 
        }
        $room =  Room::create([
            'img1' =>  $file_name1,
            'img2' => $file_name2,
            'img3' => $file_name3,
            'type_id'=> $request->type_id,
            'description'=> $request->description,
            'amount_user' => $request->amount_user,
            'status' => $request->status,
            'created_by' =>Auth::id(),
            'updated_by' => Auth::id(),
        ]);
        $room->save(); 
        return redirect('/rooms')->with('message','Room created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $room = Room::where('id',$id)->first();
        return view('admin.rooms.editroom',compact('room'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'type_id' => 'required|numeric',
            'description' => 'required|max:1000',
            'amount_user' => 'required|numeric',
            'status' => 'required|numeric',
        ]);
        $file_name1 = Room::where('id',$id)->first()->img1;
        $file_name2 = Room::where('id',$id)->first()->img2;
        $file_name3 = Room::where('id',$id)->first()->img3;
        if ($request->file('img1')) {
            $destinationPath = public_path('images/rooms');
            $files = $request->file('img1');
            $file_name = $files->getClientOriginalName(); 
            $file_name1 = $file_name;
            $files->move($destinationPath , $file_name); 
        } 
        if ($request->file('img2')) {
            $destinationPath = public_path('images/rooms');
            $files = $request->file('img2');
            $file_name = $files->getClientOriginalName();
            $file_name2 = $file_name; 
            $files->move($destinationPath , $file_name); 
        } 
        if ($request->file('img3')) {
            $destinationPath = public_path('images/rooms');
            $files = $request->file('img3');
            $file_name = $files->getClientOriginalName(); 
            $file_name3 = $file_name;
            $files->move($destinationPath , $file_name); 
        }
        $room = Room::where('id',$id)->first();
        $room->img1 = $file_name1;
        $room->img2 = $file_name2;
        $room->img3 = $file_name3;
        $room->type_id = $request->type_id;
        $room->description = $request->description;
        $room->amount_user = $request->amount_user;
        $room->status = $request->status;
        $room->updated_by = Auth::id();
        $room->updated_at = now(); 
        $room->update();
        return redirect('/rooms')->with('message', 'Room updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $bookings = Booking::where('room_id',$id)->get();
        foreach($bookings as $booking) {
            $booking->delete();
        }
        $room = Room::where('id',$id)->first();
        $room->delete();
        return redirect('/rooms')->with('message', 'Room deleted!');
    }
}

resources/views/admin/rooms/createroom.blade.php
@extends('adminLayout')
@section('content')
<style>
.btn-file {
    position: relative;
    overflow: hidden;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}

#img-upload-1{
    width: 100%;
}
#img-upload-2{
    width: 100%;
}
#img-upload-3{
    width: 100%;
}
</style>
<div class="right_col" style="min-height: 953px;">
    <div class="row mt-2">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_content">
<h1 style="text-align: center;">Create Room</h1>
<form action="{{route('rooms.store')}}" method="post" enctype="multipart/form-data">
@csrf       
    <div class="form-group">
        <div class="form-row" style="margin-top: 80px;">
            <div class="col">
                    <label>Image 1</label>
                <div class="input-group">
                    <span class="input-group-btn">
                        <span class="btn btn-default btn-file">
                            Browse… <input type="file" id="imgInp-1" name="img1">
                        </span>
                    </span>
                    <input type="text" class="form-control" readonly >
                </div>
                <img id='img-upload-1'/>
            </div>
            <div class="col">
                    <label>Image 2</label>
                <div class="input-group">
                    <span class="input-group-btn">
                        <span class="btn btn-default btn-file">
                            Browse… <input type="file" id="imgInp-2" name="img2">
                        </span>
                    </span>
                    <input type="text" class="form-control" readonly >
                </div>
                <img id='img-upload-2'/>
            </div>
            <div class="col">
                    <label>Image 3</label>
                <div class="input-group">
                    <span class="input-group-btn">
                        <span class="btn btn-default btn-file">
                            Browse… <input type="file" id="imgInp-3" name="img3">
                        </span>
                    </span>
                    <input type="text" class="form-control" readonly >
                </div>
                <img id='img-upload-3'/>
            </div>
        </div>
        <label for="">Type room:</label>
        <select name="type_id" id="" class="form-control">
            <option value="1">Standard Room</option>
            <option value="2">Intermediate Room</option>
            <option value="3">Luxury Room</option>
            <option value="4">VIP Room</option>
            <option value="5">Presidential Room</option>
        </select>
        <label for="">Description:</label>
        <textarea type="text" name="description" id="" class="form-control"></textarea>
        <label for="">Amount people:</label>
        <select name="amount_user" id="" class="form-control">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
        </select>   
        <label for="">Status:</label>
        {{-- <input type="number" name="status" id="" class="form-control"> --}}
        <select name="status" id="" class="form-control">
            <option value="1">Active</option>
            <option value="2">Close</option>
        </select>
        <button class="btn btn-primary" style="margin-left: 45%;margin-top: 20px;">Submit</button>
    </div>
    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@if ($errors->any())
            <div id="snackbar">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
                <script>
                    var x = document.getElementById("snackbar");
                    x.className = "show";
                    setTimeout(function() {
                        x.className = x.className.replace("show", "");
                    }, 5000);
                </script>
            <br />
        @endif
<script>
$(document).ready( function() {
    $(document).on('change', '.btn-file :file', function() {
		var input = $(this),
			label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
		input.trigger('fileselect', [label]);
		});

		$('.btn-file :file').on('fileselect', function(event, label) {
		var input = $(this).parents('.input-group').find(':text'),
		log = label;
		if( input.length ) {
		input.val(log);
		} else {
		if( log ) alert(log);
		}
		});
		function readURL(input) {
		if (input.files && input.files[0]) {
		var reader = new FileReader();
		reader.onload = function (e) {
		$('#img-upload-1').attr('src', e.target.result);
		}
		reader.readAsDataURL(input.files[0]);
		}
		}
		$("#imgInp-1").change(function(){
		readURL(this);
		}); 	
	});
    // ------------------------
    $(document).ready( function() {
    $(document).on('change', '.btn-file :file', function() {
		var input = $(this),
			label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
		input.trigger('fileselect', [label]);
		});

		$('.btn-file :file').on('fileselect', function(event, label) {
		var input = $(this).parents('.input-group').find(':text'),
		log = label;
		if( input.length ) {
		input.val(log);
		} else {
		if( log ) alert(log);
		}
		});
		function readURL(input) {
		if (input.files && input.files[0]) {
		var reader = new FileReader();
		reader.onload = function (e) {
		$('#img-upload-2').attr('src', e.target.result);
		}
		reader.readAsDataURL(input.files[0]);
		}
		}

		$("#imgInp-2").change(function(){
	    readURL(this);
		}); 	
	});
    // -----------------
    $(document).ready( function() {
    	$(document).on('change', '.btn-file :file', function() {
		var input = $(this),
			label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
		input.trigger('fileselect', [label]);
		});

		$('.btn-file :file').on('fileselect', function(event, label) {
		    var input = $(this).parents('.input-group').find(':text'),
		        log = label;
		    
		    if( input.length ) {
		        input.val(log);
		    } else {
		        if( log ) alert(log);
		    }
	    
		});
		function readURL(input) {
		    if (input.files && input.files[0]) {
		        var reader = new FileReader();
		        
		        reader.onload = function (e) {
		            $('#img-upload-3').attr('src', e.target.result);
		        }
		        
		        reader.readAsDataURL(input.files[0]);
		    }
		}

		$("#imgInp-3").change(function(){
		    readURL(this);
		}); 	
	});
</script>
@endsection

resources/views/admin/rooms/room.blade.php
@extends ('adminLayout')
@section('content')
<style>
.tableimage {
    padding: 0 0 0 0;
    width: 150px;
}
</style>
<div class="right_col" style="min-height: 953px;">
    <h1 style="text-align:center;">Rooms</h1>
    <form action="" method="GET" class="frmsearch" id="searchform">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text widthcol2" id="basic-addon1" style="width: 95px;">ID:</span>
                        </div>
                        <input type="text" id="id" class="form-control" name="id" placeholder="Enter id room"
                            maxlength="10" aria-label="Username" aria-describedby="basic-addon1"
                            value="{{request()->get('id')}}">
                    </div>
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text widthcol2" id="basic-addon1" style="width: 95px;">Type:</span>
                        </div>
                        <input type="text" id="name" class="form-control" name="type" placeholder="Enter name type"
                            aria-label="Username" aria-describedby="basic-addon1" value="{{request()->get('type')}}"
                            maxlength="115">
                    </div>
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text widthcol2" id="basic-addon1"
                                style="width: 95px;">Status:</span>
                        </div>
                        <select name="status" id="status" class="form-control" onchange="javascript:this.form.submit()">
                            <option value="0" @if(request()->status== '0') selected @endif>All</option>
                            <option value="1" @if(request()->status== '1') selected @endif>Active</option>
                            <option value="2" @if(request()->status== '2') selected @endif>Close</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row" style="margin: 20px">
                <div class="col-md-4"></div>
                <div class=" col-12 col-ms-8 col-md-8 col-xs-6">
                    <button type="submit" class="btn btn-primary col search" style="width:25%;">Search</button>
                    <a href="{{route('rooms.create')}}" class="">
                        <button type="button" class="btn btn-info col" style="width:25%;">Create</button>
                    </a>
                </div>
            </div>
        </div>
    </form>
    <div class="row mt-2">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_content">
    <table class="table table-striped">
        <thead>

            <tr>
                <th scope="col">STT</th>
                <th scope="col">ID</th>
                <th scope="col">Image 1</th>
                <th scope="col">Image 2</th>
                <th scope="col">Image 3</th>
                <th scope="col">Type</th>
                <th scope="col">Amount People</th>
                <th scope="col">Price</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php $count = 1; ?>
            @foreach ($rooms as $room)
            <tr>
                <th scope="row">{{$rooms->perPage()*($rooms->currentPage()-1)+$count}}</th>
                <td>{{$room->id}}</td>
                <td class="tableimage"><img src="{{ asset('images/rooms/'.$room->img1)}}" style="height:50px; width: 100px;"></td>
                <td class="tableimage"><img src="{{ asset('images/rooms/'.$room->img2)}}" style="height:50px; width: 100px;"></td>
                <td class="tableimage"><img src="{{ asset('images/rooms/'.$room->img3)}}" style="height:50px; width: 100px;"></td>
                <td>{{$room->type_name}}</td>
                <td>{{$room->amount_user}}</td>
                <td>{{$room->type_price*$room->amount_user}}$</td>
                @if($room->status == 1)
                <td style="color:green; font-weight:bold;"><i class="fa fa-check-circle fa-3x" aria-hidden="true"></i></td>
                @elseif($room->status ==2 )
                <td style="color:red; font-weight:bold;"><i class="fa fa-times-circle fa-3x" aria-hidden="true"></i></td>
                @endif
                <td>
                    <a href="{{route('rooms.edit', $room->id) }}" style="color:blue;">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-pencil-square"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd"
                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                    </a>
                    <a href="" data-toggle="modal" data-target="#exampleModal"
                        onClick="onClickDelete({{$room->id}})" style="color:red;">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd"
                                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                </td>
            </tr>
            <?php $count++; ?>
            @endforeach
        </tbody>
    </table>
    <form style="display:inline" action="" method="post" id="delete-form">
        @csrf
        @method('DELETE')
        <div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content" style="border-radius: 1rem;">
                    <div class="modal-header" style="background-color: #2A3F54;">
                        <h5 class="modal-title" id="exampleModalLabel" style="color:white;">DELETE</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h1 style="text-align:center;">Are you sure?</h1>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"
                            style="width: 100px;">Close</button>
                        <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#successdelete"
                            onClick="submitdelete()" style="width: 67px;">Yes</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="d-flex justify-content-end nav">
        {!! $rooms->withQueryString()->links('pagination.paginate') !!}
    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@if (Session::has('message'))
<div id="snackbar">{{ Session::get('message') }}</div>
<script>
    var x = document.getElementById("snackbar");
    x.className = "show";
    setTimeout(function() {
        x.className = x.className.replace("show", "");
    }, 3000);
</script>
</div>
@endif
<script>
    const onClickDelete = (id) => {
        const deleteForm = document.getElementById('delete-form');
        deleteForm.action = '/rooms/' + id;
    };
    
    function submitdelete() {
        const deleteForm = document.getElementById('delete-form');
        deleteForm.submit();
    }
    </script>
@endsection