routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HotelController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\TypeRoomController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\Auth\{LoginController, RegisterController, ResetPasswordController};
use App\Http\Middleware\{User, Admin};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
# Login & Register & Forgot password
Route::post('/send_login', [LoginController::class, 'sendLogin'])->name('sendLogin');
Route::post('/send_register', [RegisterController::class, 'sendRegister'])->name('sendRegister');
Route::post('/send_email_password', [ResetPasswordController::class, 'sendEmailPassword'])->name('sendEmailPassword');
Route::get('/logout', [LoginController::class, 'doLogout'])->name('doLogout');
Route::get('/logoutadmin',[LoginController::class,'doLogoutAdmin'])->name('doLogoutAdmin');
# End Login & Register & Forgot password
# Customer
Route::get('/user_profile', [CustomerController::class, 'index'])->name('profile')->middleware(User::class);
Route::get('/user_profile_edit', [CustomerController::class, 'showPageEdit'])->name('showPageEdit')->middleware(User::class);
Route::post('/send_user_edit', [CustomerController::class, 'doUserEdit'])->name('doUserEdit')->middleware(User::class);
Route::post('/changeavatar',[CustomerController::class,'changeAvatar'])->middleware(User::class);
Route::get('/user_password_change', [CustomerController::class, 'showPasswordChange'])->name('showPasswordChange')->middleware(User::class);
Route::post('/send_password_change', [CustomerController::class, 'doChangePassword'])->name('doChangePassword')->middleware(User::class);
Route::get('/history',[CustomerController::class, 'showHistory'])->name('showHistory')->middleware(User::class);
# End customer

Route::get('/', [HotelController::class,'home'])->name('home');
Route::get('/room', [HotelController::class,'room'])->name('room');
Route::get('/about', [HotelController::class,'aboutus'])->name('aboutus');
Route::get('/cart',[CustomerController::class,'showCart'])->name('cart');
Route::get('/detailroom={id}',[HotelController::class,'detailroom'])->name('detailroom');
Route::get('/admin/employee',[AdminController::class,'employee'])->name('employee')->middleware(Admin::class);
Route::post('/postRate/{id}', [HotelController::class, 'postRate'])->name('postrate')->middleware(User::class);
Route::get('/admin',[AdminController::class,'index'])->name('adminindex')->middleware(Admin::class);
Route::get('/admin/profile',[AdminController::class,'profile'])->name('adminprofile')->middleware(Admin::class);
Route::put('/admin/profile',[AdminController::class,'editprofile'])->name('updateprofile')->middleware(Admin::class);
Route::put('/admin/profile/newpass',[AdminController::class,'doChangePassword'])->name('changepassadmin')->middleware(Admin::class);
Route::put('/admin/profile/newavatar',[AdminController::class,'changeAvatar'])->name('changeavatar')->middleware(Admin::class);
Route::resource('rooms', RoomController::class)->middleware(Admin::class);
Route::resource('types', TypeRoomController::class)->middleware(Admin::class);
Route::resource('bookings', BookingController::class)->middleware(Admin::class);
Route::resource('employees', EmployeeController::class)->middleware(Admin::class);
Route::resource('services', ServiceController::class)->middleware(Admin::class);
Route::resource('message', MessageController::class)->middleware(Admin::class);
Route::get('/contact', [MessageController::class,'create'])->name('contact');
Route::get('/profile',[CustomerController::class,'index'])->name('profile')->middleware(User::class);
Route::get('/bookings/bill/{id}',[BookingController::class,'printbill'])->name('bill')->middleware(Admin::class);
Route::delete('/cart/{id}',[CustomerController::class,'destroy'])->name('deletecart')->middleware(User::class);
#Resetpass with mail
Route::get('/resetpassword=token={token}',[CustomerController::class,'getChangePass']);
Route::post('/change-password-with-token',[CustomerController::class,'postChangePass']);


// Route::get('/admin/room',[RoomController::class,'index'])->name('adminrooms');
// Route::get('/admin/user',[UserController::class,'index'])->name('adminusers');
// Route::get('/admin/booking',[BookingController::class,'index'])->name('adminbookings');
// Route::get('/admin/employee',[EmployeeController::class,'index'])->name('adminemployees');
// Route::get('/admin/services',[ServiceController::class,'index'])->name('adminservices');
// Route::get('/admin/user/create',[UserController::class,'create'])->name('usercreate');
Route::resource('users', UserController::class);
Route::get('/reset',function(){
    return view('emails.mailreset');
});
Route::get('/admin/bill', function(){
    return view('admin.bookings.bill');
});
Route::get('/admin/login', function() {
    return view('admin.login');
});
Route::get('admin/editbooking',function(){
return view('admin.bookings.editbooking');
});
Route::post('/send-login-admin', [LoginController::class, 'doLoginAdmin']);
// Route::get('/admin/rooms/edit', function() {
//     return view('admin.rooms.editroom');
// });
Route::post('/room/{id}',[CustomerController::class,'pushToCart'])->name('pushToCart')->middleware(User::class);
Route::put('/sendBookingToAdmin/{id}',[CustomerController::class,'sendBookingToAdmin'])->name('sendBookingToAdmin')->middleware(User::class);
Route::get('/cart/{id}',[CustomerController::class,'cartAjax'])->middleware(User::class);




//Multiple langue
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

resources/views/admin/servicess/createservice.blade.php
@extends('adminLayout')
@section('content')
<div class="right_col" style="min-height: 953px;">
<h1 style="text-align: center;">Create Service</h1>
<form action="{{route('services.store')}}" method="post">
@csrf       
    <div class="form-group">
        <label for="">Name:</label>
        <input type="text" name="name" id="" class="form-control">
        <label for="">Price:</label>
        <input type="number" name="price" id="" class="form-control">
        <button class="btn btn-primary" style="margin-left: 45%;margin-top: 20px;">Submit</button>
    </div>
    </form>
</div>
@if ($errors->any())
            <div id="snackbar">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
                <script>
                    var x = document.getElementById("snackbar");
                    x.className = "show";
                    setTimeout(function() {
                        x.className = x.className.replace("show", "");
                    }, 5000);
                </script>
            <br />
        @endif
@endsection

resources/views/admin/servicess/editservice.blade.php
@extends('adminLayout')
@section('content')
<div class="right_col" style="min-height: 953px;">
<h1 style="text-align: center;">Edit Service</h1>
<form action="{{route('services.update',$service)}}" method="post">
@method('put')
@csrf       
    <div class="form-group">
        <label for="">Name:</label>
        <input type="text" name="name" id="" class="form-control" value="{{$service->name}}">
        <label for="">Price:</label>
        <input type="number" name="price" id="" class="form-control" value="{{$service->price}}">
        <button class="btn btn-primary" style="margin-left: 45%;margin-top: 20px;">Submit</button>
    </div>
    </form>
</div>
@if ($errors->any())
            <div id="snackbar">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
                <script>
                    var x = document.getElementById("snackbar");
                    x.className = "show";
                    setTimeout(function() {
                        x.className = x.className.replace("show", "");
                    }, 3000);
                </script>
            <br />
        @endif
@endsection

resources/views/admin/servicess/service.blade.php
@extends ('adminLayout')
@section('content')
<div class="right_col" style="min-height: 953px;">
    <h1 style="text-align:center;">Services</h1>
    <div class="row mt-2">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_content">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">STT</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php $count = 1; ?>
            @foreach($list_service as $service)
            <tr>
                <th scope="row">{{$count++}}</th>
                <td>{{$service->name}}</td>
                <td>{{$service->price}}$</td>
                <td>
                    <a href="{{route('services.edit', $service->id)}}" style="color:blue;">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-pencil-square"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd"
                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                    </a>
                    <a href="" data-toggle="modal" data-target="#exampleModal" onClick="onClickDelete({{$service->id}})"
                        style="color:red;">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd"
                                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                </td>
            </tr>
        </tbody>
        @endforeach
    </table>
    <form style="display:inline" action="" method="post" id="delete-form">
        @csrf
        @method('DELETE')
        <div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content" style="border-radius: 1rem;">
                    <div class="modal-header" style="background-color: #2A3F54;">
                        <h5 class="modal-title" id="exampleModalLabel" style="color:white;">DELETE</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h1 style="text-align:center;">Are you sure?</h1>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"
                            style="width: 100px;">Close</button>
                        <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#successdelete"
                            onClick="submitdelete()" style="width: 67px;">Yes</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
            </div>
        </div>
    </div>
</div>
@if (Session::has('message'))
<div id="snackbar">{{ Session::get('message') }}</div>
<script>
    var x = document.getElementById("snackbar");
    x.className = "show";
    setTimeout(function() {
        x.className = x.className.replace("show", "");
    }, 3000);

</script>
</div>
@endif
<script>
const onClickDelete = (id) => {
    const deleteForm = document.getElementById('delete-form');
    deleteForm.action = '/services/' + id;
};

function submitdelete() {
    deleteForm.submit();
}
</script>
@endsection