routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HotelController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\TypeRoomController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\Auth\{LoginController, RegisterController, ResetPasswordController};
use App\Http\Middleware\{User, Admin};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
# Login & Register & Forgot password
Route::post('/send_login', [LoginController::class, 'sendLogin'])->name('sendLogin');
Route::post('/send_register', [RegisterController::class, 'sendRegister'])->name('sendRegister');
Route::post('/send_email_password', [ResetPasswordController::class, 'sendEmailPassword'])->name('sendEmailPassword');
Route::get('/logout', [LoginController::class, 'doLogout'])->name('doLogout');
Route::get('/logoutadmin',[LoginController::class,'doLogoutAdmin'])->name('doLogoutAdmin');
# End Login & Register & Forgot password
# Customer
Route::get('/user_profile', [CustomerController::class, 'index'])->name('profile')->middleware(User::class);
Route::get('/user_profile_edit', [CustomerController::class, 'showPageEdit'])->name('showPageEdit')->middleware(User::class);
Route::post('/send_user_edit', [CustomerController::class, 'doUserEdit'])->name('doUserEdit')->middleware(User::class);
Route::post('/changeavatar',[CustomerController::class,'changeAvatar'])->middleware(User::class);
Route::get('/user_password_change', [CustomerController::class, 'showPasswordChange'])->name('showPasswordChange')->middleware(User::class);
Route::post('/send_password_change', [CustomerController::class, 'doChangePassword'])->name('doChangePassword')->middleware(User::class);
Route::get('/history',[CustomerController::class, 'showHistory'])->name('showHistory')->middleware(User::class);
# End customer

Route::get('/', [HotelController::class,'home'])->name('home');
Route::get('/room', [HotelController::class,'room'])->name('room');
Route::get('/about', [HotelController::class,'aboutus'])->name('aboutus');
Route::get('/cart',[CustomerController::class,'showCart'])->name('cart');
Route::get('/detailroom={id}',[HotelController::class,'detailroom'])->name('detailroom');
Route::get('/admin/employee',[AdminController::class,'employee'])->name('employee')->middleware(Admin::class);
Route::post('/postRate/{id}', [HotelController::class, 'postRate'])->name('postrate')->middleware(User::class);
Route::get('/admin',[AdminController::class,'index'])->name('adminindex')->middleware(Admin::class);
Route::get('/admin/profile',[AdminController::class,'profile'])->name('adminprofile')->middleware(Admin::class);
Route::put('/admin/profile',[AdminController::class,'editprofile'])->name('updateprofile')->middleware(Admin::class);
Route::put('/admin/profile/newpass',[AdminController::class,'doChangePassword'])->name('changepassadmin')->middleware(Admin::class);
Route::put('/admin/profile/newavatar',[AdminController::class,'changeAvatar'])->name('changeavatar')->middleware(Admin::class);
Route::resource('rooms', RoomController::class)->middleware(Admin::class);
Route::resource('types', TypeRoomController::class)->middleware(Admin::class);
Route::resource('bookings', BookingController::class)->middleware(Admin::class);
Route::resource('employees', EmployeeController::class)->middleware(Admin::class);
Route::resource('services', ServiceController::class)->middleware(Admin::class);
Route::resource('message', MessageController::class)->middleware(Admin::class);
Route::get('/contact', [MessageController::class,'create'])->name('contact');
Route::get('/profile',[CustomerController::class,'index'])->name('profile')->middleware(User::class);
Route::get('/bookings/bill/{id}',[BookingController::class,'printbill'])->name('bill')->middleware(Admin::class);
Route::delete('/cart/{id}',[CustomerController::class,'destroy'])->name('deletecart')->middleware(User::class);
#Resetpass with mail
Route::get('/resetpassword=token={token}',[CustomerController::class,'getChangePass']);
Route::post('/change-password-with-token',[CustomerController::class,'postChangePass']);


// Route::get('/admin/room',[RoomController::class,'index'])->name('adminrooms');
// Route::get('/admin/user',[UserController::class,'index'])->name('adminusers');
// Route::get('/admin/booking',[BookingController::class,'index'])->name('adminbookings');
// Route::get('/admin/employee',[EmployeeController::class,'index'])->name('adminemployees');
// Route::get('/admin/services',[ServiceController::class,'index'])->name('adminservices');
// Route::get('/admin/user/create',[UserController::class,'create'])->name('usercreate');
Route::resource('users', UserController::class);
Route::get('/reset',function(){
    return view('emails.mailreset');
});
Route::get('/admin/bill', function(){
    return view('admin.bookings.bill');
});
Route::get('/admin/login', function() {
    return view('admin.login');
});
Route::get('admin/editbooking',function(){
return view('admin.bookings.editbooking');
});
Route::post('/send-login-admin', [LoginController::class, 'doLoginAdmin']);
// Route::get('/admin/rooms/edit', function() {
//     return view('admin.rooms.editroom');
// });
Route::post('/room/{id}',[CustomerController::class,'pushToCart'])->name('pushToCart')->middleware(User::class);
Route::put('/sendBookingToAdmin/{id}',[CustomerController::class,'sendBookingToAdmin'])->name('sendBookingToAdmin')->middleware(User::class);
Route::get('/cart/{id}',[CustomerController::class,'cartAjax'])->middleware(User::class);




//Multiple langue
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

app/Models/User.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\{Role, Booking};
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Illuminate\Auth\Authenticatable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;

class User extends Model implements AuthenticatableContract
{
    use SoftDeletes;
    use HasFactory;
    use Authenticatable;
    
    protected $table = 'users';
    protected $guarded = [];
    protected $fillable = [
        'name', 'email', 'password',
    ];
    protected $hidden = [
    'password', 'remember_token','deleted_at'
    ];
    public function roles(){
        return $this->belongsTo(Role::class);
    }

    public function bookings(){
        return $this->hasMany(Booking::class);
    }

    public function delete()
    {
        DB::transaction(function () {
            $this->bookings()->delete();
            return parent::delete();
        });
    } 
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Models\User;
use App\Models\Role;
use App\Models\Rate;
use App\Models\Booking;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = User::join('roles', 'users.role_id', '=','roles.id');
        $users = $query
                        ->select('users.*','roles.name as role_name')
                        ->whereIn('role_id',[1,3])
                        ->paginate(10);
        if($request->id){
            $id = $request->id;
            $users = $query
                        ->where('users.id',$id)
                        ->paginate(10);
        }
        if($request->name){
            $name =$request->name;
            $users = $query
                        ->where('users.name','LIKE', "%" . $name . "%")
                        ->paginate(10);
        }
        if($request->role){
            $role = $request->role;
            $users = $query
                    ->where('roles.name', 'LIKE', "%" . $role . "%")
                    ->paginate(10);
        }
        return view('admin.users.user', compact('users'));
    }
    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('admin.users.createuser',['users'=>$roles]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'email'=>'required|max:100|regex:/^.+@.+$/i|email|unique:users',
            'password'=>'required|max:50|',
            'name' => 'required|max:200',
            'birth_day' => 'required|date',
            'address' => 'required|max:255',
            'identify_card' => 'required|max:15',
            'phone' => 'required|max:15',
            'status' => 'required',
            'role_id' => 'required'
        ]);
        $user = new User;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->name = $request->name;
        $user->gender = $request->gender;
        $user->birth_day = $request->birth_day;
        $user->address = $request->address;
        $user->identify_card = $request->identify_card;
        $user->phone = $request->phone;
        $user->status = $request->status;
        $user->role_id = $request->role_id;
        $user->created_by = Auth::id();
        $user->save();
        return redirect('/users')->with('message', 'User created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $user = User::where('id',$id)->first();
        return view('admin.users.edituser',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'email'=>'required|max:100|regex:/^.+@.+$/i',
            'name' => 'required|max:200',
            'status' => 'required',
            'role_id' => 'required'
        ]);
        $user = User::where('id',$id)->first();
        $user->email = $request->email;
        $user->name = $request->name;
        $user->status = $request->status;
        $user->role_id = $request->role_id;
        $user->update();
        return redirect('/users')->with('message', 'User updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $rates = Rate::where('user_id',$id)->get();
        foreach($rates as $rate) {
            $rate->delete();
        }
        $bookings = Booking::where('user_id',$id)->get();
        foreach($bookings as $booking) {
            $booking->delete();
        }
        $user = User::where('id',$id)->first();
        $user->delete();
        return redirect('/users')->with('message', 'User deleted!');
    }
}

resources/views/admin/users/createuser.blade.php
@extends('adminLayout')
@section('content')
<div class="right_col" style="min-height: 953px;">
    <div class="row mt-2">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_content">
                    <h1 style="text-align: center;">Create User</h1>
                    <form action="{{route('users.store')}}" method="post" id="form-create">
                        @csrf       
                    <div class="form-group">
                    <label for="">Email:</label>
                    <input type="text" name="email" id="" class="form-control">
                    </div>
                    <div class="form-group">
                    <label for="">Password:</label>
                    <input type="text" name="password" id="" class="form-control">
                    </div>
                    <div class="form-group">
                    <label for="">Name:</label>
                    <input type="text" name="name" id="" class="form-control">
                    </div>
                    <div class="form-group">
                    <label for="">Gender:</label>
                    <select class="form-control" name="gender" id="">
                        <option value="1">Man</option>
                        <option value="2">Lady</option>
                    </select>
                    </div>
                    <div class="form-group">
                    <label for="">Birth day:</label>
                    <input type="date" name="birth_day" id="" class="form-control">
                    </div>
                    <div class="form-group">
                    <label for="">Address:</label>
                    <input type="text" name="address" id="" class="form-control">
                    </div>
                    <div class="form-group">
                    <label for="">Identify Card:</label>
                    <input type="text" name="identify_card" id="" class="form-control">
                    </div>
                    <div class="form-group">
                    <label for="">Phone:</label>
                    <input type="text" name="phone" id="" class="form-control">
                    </div>
                    <div class="form-group">
                    <label for="">Status:</label>
                    <select class="form-control" name="status" id="">
                        <option value="0">Lock</option>
                        <option value="1">Active</option>
                    </select>
                    </div>
                    <div class="form-group">
                    <label for="">Role: </label>
                    <Select class="form-control" name="role_id">
                        <option value="1">Admin</option>
                        <option value="2">Employee</option>
                        <option value="3">Customer</option>
                    </Select>
                    </div>
                    <button class="btn btn-primary" style="margin-left: 45%;margin-top: 20px;">Submit</button>
                
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@if ($errors->any())
            <div id="snackbar">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
                <script>
                    var x = document.getElementById("snackbar");
                    x.className = "show";
                    setTimeout(function() {
                        x.className = x.className.replace("show", "");
                    }, 5000);
                </script>
            <br />
        @endif
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
    <script>
    $("#form-create").validate({
    rules: {
        email: {
            required: true,
            maxlenght: 20,
            email: true,
        },
        password: {
            required: true,
        },
        name: {
            required: true,
        },
        gender: {
            required: true,
        },
        birth_day: {
            required: true,
            date: true,
        },
        address: {
            required: true,
            maxlenght: 2000,
        },
        identify_card: {
            required: true,
            number: true,
        },
        phone: {
            required: true,
            number: true,
        },
        status: {
            required: true,
        }
        ,
        role_id: {
            required: true,
        }
    },
    errorElement: 'span',
    errorPlacement: function(error, element) {
        error.addClass('invalid-feedback');
        element.closest('.form-group').append(error);
    },
    highlight: function(element, errorClass, validClass) {
        $(element).addClass('is-invalid');
    },
    unhighlight: function(element, errorClass, validClass) {
        $(element).removeClass('is-invalid');
    }
});
</script>
@endsection

resources/views/admin/users/edituser.blade.php
@extends('adminLayout')
@section('content')
<div class="right_col" style="min-height: 953px;">
    <div class="row mt-2">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_content">
<h1 style="text-align: center;">Edit User</h1>
<form action="{{route('users.update',$user)}}" method="post">
@method('put') 
@csrf
<div class="form-group">
        <label for="">Email:</label>
        <input type="text" name="email" id="" class="form-control" value="{{$user->email}}">
        <label for="">Name:</label>
        <input type="text" name="name" id="" class="form-control" value="{{$user->name}}">
        <label for="">Status:</label>
        <select class="form-control" name="status" id="">
            @if($user->status == 0)
            <option value="0">Lock</option>
            <option value="1">Active</option>
            @else
            <option value="1">Active</option>
            <option value="0">Lock</option>
            @endif
        </select>
        <label for="">Role: </label>
        <Select class="form-control" name="role_id">
            <option value="1">Admin</option>
            <option value="2">Employee</option>
            <option value="3">Customer</option>
        </Select>
        <button class="btn btn-primary" style="margin-left: 45%;margin-top: 20px;">Submit</button>
    </div>
</form>
                </div>
            </div>
        </div>
    </div>
</div>
@if ($errors->any())
            <div id="snackbar">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
                <script>
                    var x = document.getElementById("snackbar");
                    x.className = "show";
                    setTimeout(function() {
                        x.className = x.className.replace("show", "");
                    }, 3000);
                </script>
            <br />
        @endif
@endsection

resources/views/admin/users/user.blade.php
@extends('adminLayout')
@section('content')
<div class="right_col" style="min-height: 953px;">
    <h1 style="text-align:center;">Users</h1>
    <form action="" method="GET" class="frmsearch" id="searchform">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text widthcol2" id="basic-addon1" style="width: 95px;">ID:</span>
                        </div>
                        <input type="text" id="id" class="form-control" name="id" placeholder="Enter id user"
                            maxlength="10" aria-label="Username" aria-describedby="basic-addon1"
                            value="{{request()->get('id')}}">
                    </div>
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text widthcol2" id="basic-addon1" style="width: 95px;">Name:</span>
                        </div>
                        <input type="text" id="name" class="form-control" name="name" placeholder="Enter name user"
                            aria-label="Username" aria-describedby="basic-addon1" value="{{request()->get('name')}}"
                            maxlength="115">
                    </div>
                </div>
                <div class="col">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text widthcol2" id="basic-addon1" style="width: 95px;">Role:</span>
                        </div>
                        <input type="text" id="role" class="form-control" name="role" placeholder="Enter role"
                            aria-label="Username" aria-describedby="basic-addon1" value="{{request()->get('role')}}"
                            maxlength="115">
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row" style="margin: 20px">
                <div class="col-md-4"></div>
                <div class=" col-12 col-ms-8 col-md-8 col-xs-6">
                    <button type="submit" class="btn btn-primary col search" style="width:25%;">Search</button>
                    <a href="{{route('users.create')}}" class="">
                        <button type="button" class="btn btn-info col" style="width:25%;">Create</button>
                    </a>
                </div>
            </div>
        </div>
    </form>
    <div class="row mt-2">
        <div class="col-md-12 col-sm-12">
            <div class="x_panel">
                <div class="x_content">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">STT</th>
                <th scope="col">ID</th>
                <th scope="col">Role</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Gender</th>
                <th scope="col">Birth day</th>
                <th scope="col">Address</th>
                <th scope="col">Identify Card</th>
                <th scope="col">Phone</th>
                <th scope="col">Status</th>
                @if(Auth::user()->role_id == 1)
                <th scope="col">Action</th>
                @endif
            </tr>
        </thead>
        <tbody>
            <?php $count = 1; ?>
            @foreach($users as $user)
            <tr>
                <th scope="row">{{$users->perPage()*($users->currentPage()-1)+$count}}</th>
                <td>{{$user->id}}</td>
                <td>{{$user->role_name}}</td>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                @if($user->gender == 1)
                <td>Man</td>
                @elseif($user->gender == 2)
                <td>Lady</td>
                @else
                <td></td>
                @endif
                <td>{{$user->birth_day}}</td>
                <td>{{$user->address}}</td>
                <td>{{$user->identify_card}}</td>
                <td>{{$user->phone}}</td>
                @if($user->status == 0)
                <td style="color:red; font-weight:bold;"><i class="fa fa-ban fa-3x" aria-hidden="true"></i></td>
                @else
                <td style="color:green;font-weight:bold;"><i class="fa fa-check-circle-o fa-3x" aria-hidden="true"></i></td>
                @endif
                @if(Auth::user()->role_id == 1)
                <td>
                    <a href="{{route('users.edit', $user->id) }}" style="color:blue;">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-pencil-square"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd"
                                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                    </a>
                    <a href="" data-toggle="modal" data-target="#exampleModal" onClick="onClickDelete({{$user->id}})"
                        style="color:red;">
                        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                            <path fill-rule="evenodd"
                                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                        </svg>
                    </a>
                </td>
                @endif
            </tr>

        </tbody>
        <?php $count++; ?>
        @endforeach
    </table>
    <form style="display:inline" action="" method="post" id="delete-form">
        @csrf
        @method('DELETE')
        <div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content" style="border-radius: 1rem;">
                    <div class="modal-header" style="background-color: #2A3F54;">
                        <h5 class="modal-title" id="exampleModalLabel" style="color:white;">DELETE</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h1 style="text-align:center;">Are you sure?</h1>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"
                            style="width: 100px;">Close</button>
                        <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#successdelete"
                            onClick="submitdelete()" style="width: 67px;">Yes</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="d-flex justify-content-end nav">
        {!! $users->withQueryString()->links('pagination.paginate') !!}
    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@if (Session::has('message'))
<div id="snackbar">{{ Session::get('message') }}</div>
<script>
    var x = document.getElementById("snackbar");
    x.className = "show";
    setTimeout(function() {
        x.className = x.className.replace("show", "");
    }, 3000);

</script>
</div>
@endif
<script>
const onClickDelete = (id) => {
    const deleteForm = document.getElementById('delete-form');
    deleteForm.action = '/users/' + id;
};

function submitdelete() {
    deleteForm.submit();
}
</script>

@endsection